### PR TITLE
fix: update under-pressure

### PR DESCRIPTION
**Pull request by Eomm**
ref https://github.com/fastify/under-pressure/issues/184

### CODE REVIEW

**Review by SimenB — APPROVED** [review]
sweet 👍

**Comment by Uzlopak** [comment]
What is with the package-lock? It did not change. So i assume you just touched the package json without doing an npm i.
Can we actually drop the package-lock generation?

**Review by Uzlopak — CHANGES_REQUESTED** [review]
What is with the package lock?

**Review by Uzlopak — APPROVED** [review]
fixed the package-lock

**Comment by SimenB** [comment]
release? 😀

**Comment by SimenB** [comment]
@mcollina could you release this please? 😀 I need https://github.com/fastify/fastify-plugin/pull/193 to be in semver range 🙂

**Pull request merged**
