### PR TITLE
upgrade nextjs to v11

### PR DESCRIPTION
**Pull request by tomasstrejcek**
Just changing the version as noted in #279, everything seems to work just fine.

#### Checklist

- [x] run `npm run test` 
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
CI is failing. I think you need to remove package-lock and reinstall with npm v6.

**Comment by kibertoad** [comment]
@mcollina Do we even need package-lock committed?

**Comment by mcollina** [comment]
Unfortunately we do. The dependencies of this module are brittle and they often break CI in minor version :/.

**Comment by tomasstrejcek** [comment]
alright @mcollina what version of node would you recommend? Node.js 14.17.1 with npm 6.14.13 is ok?

**Comment by tomasstrejcek** [comment]
also some readme update could be beneficial for "next time"? :)

**Comment by tomasstrejcek** [comment]
fyi nvm didnt find arm binaries for 14.7.1 and build from source failed so I went with rosetta run 14.16.0 🤷

**Comment by kibertoad** [comment]
> The dependencies of this module are brittle and they often break CI in minor version :/.

Does that include transitive dependencies, or only the ones we rely upon directly? We may want to enforce stricter version ranges instead of using package-lock.

**Comment by mcollina** [comment]
It's often transitive dependencies.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
