### PR TITLE
Add Next 12 in peerDependencies

### PR DESCRIPTION
**Pull request by scantarbian**
We have Next 12 now (https://github.com/vercel/next.js/releases/tag/v12.0.0), it's better to add them in peerDependencies so we don't need to use --force when installing

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by climba03003** [comment]
Can you update the `next` in dev dependency and run the test to ensure everything works fine?

**Comment by scantarbian** [comment]
Sure, pushed the updated dev dependency and it passes the test
image

**Comment by scantarbian** [comment]
Hmm, checks are failing though

**Comment by climba03003** [comment]
https://nextjs.org/docs/upgrading#minimum-nodejs-version

It drops `node@10` supports, please remove the github action about `node@10`. I will bump a major for this change.

**Comment by scantarbian** [comment]
Do you think we should also add checking for Node 17?

**Comment by climba03003** [comment]
> 
> 
> Do you think we should also add checking for Node 17?

In my point of view, no. It is a short life version and any drop of support need a major bump.

**Review by climba03003 — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
