### PR TITLE
Make `opts.schema` optional

### PR DESCRIPTION
**Pull request by rbeer**
Using `schema` validation creates
  problems on NextJs API routes.

  TSC complaining about the missing
  field makes it seem like `schema`
  is required, while it's really not.

  ref: fastify/help#582

#### Checklist

- [x] run `npm run test` ~and `npm run benchmark`~
- [ ] tests and/or benchmarks are included
- [ ] ~documentation is changed or added~
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
Can you please add a unit test? We test our types using `tsd`.

**Comment by rbeer** [comment]
That's going to take me a bit, since I've never done that. Will have to read up on that, tonight; but generally yes, of course.

**Comment by rbeer** [comment]
There kind of was a unit test with `types.test.ts` which was simply run through `tsc` in the test script.
I had to add `tsd` itself and rename the file to `index.test-d.ts` to meet `tsd`'s standard.
I removed the `typescript` dependency, since there aren't any typescript files in the repo, other than the `index.test-d.ts` which is handled by `tsd`.

(force-push due to rebase of the earlier accepted PR)

**Review by mcollina — COMMENTED** [review]
Good work! Can you remove the package-lock file and add it to .gitignore?

**Comment by rbeer** [comment]
> Good work! Can you remove the package-lock file and add it to .gitignore?

#238 not a thing, anymore? Just checking :)

**Comment by mcollina** [comment]
Ah damn, good catch. Leave it there, don't worry about it.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
