### PR TITLE
upgrade to fastify 4 and latest under pressure

### LINKED ISSUE #549: Fastify v4 error: "under-pressure - expected '3.x' fastify version, '4.0.0' is installed"
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

8.0.0

### Node.js version

16.13.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.1

### Description

When using @fastify/nextjs with the underPressure option an unexpected plugin version error is thrown.

### Steps to Reproduce

1. Use fastify v4 and plugin v8
2. Configure plugin with any `underPressure` options
3. Error is thrown due to https://github.com/fastify/fastify-nextjs/blob/6449bfd7a50744dc862faaba910fdd8edba48c56/index.js#L13, and https://github.com/fastify/fastify-nextjs/blob/6449bfd7a50744dc862faaba910fdd8edba48c56/package.json#L49

### Expected Behavior

No error is thrown when using `underPressure` options.

### LINKED ISSUE #557: Update to Fastify v4
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently the update to Fastify v4 is blocked by latest Next.js being incompatible with this module testing approach (#555).

After that is solved, we would need to update this module to Fastify v4. 

### Motivation

_No response_

### Example

_No response_

### PR DESCRIPTION
**Pull request by Uzlopak**
resolves #557 
resolves #549 
closes #588 
closes #563 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
@mcollina 
this means of course a semver major release.

**Comment by drakhart** [comment]
Looks good to me. 👍

**Review by simoneb — APPROVED** [review]

**Comment by SimenB** [comment]
Release incoming? 😀

**Comment by Eomm** [comment]
released 👍🏽

**Comment by SimenB** [comment]
Great, thanks!

**Pull request merged**
