### PR TITLE
fix (coverage): remove statements not needed since `fastify@3.22.1`

### PR DESCRIPTION
**Pull request by darkgl0w**
Hello.

This PR aims to :
- remove 2 statements that are not needed since the release of `fastify@3.22.1`
- unlock the upgrade of `fastify` dependency by our GitHub action workflow
- upgrade package dependencies (fix https://github.com/fastify/fastify-nextjs/issues/470)

For reference: 
- the PR that introduced the behavior: https://github.com/fastify/fastify/pull/2546
- the PR that fixed the behavior: https://github.com/fastify/fastify/pull/3375

#### Checklist

- [x] run `npm run test` ~~and `npm run benchmark`~~
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
I would just remove both statements, we only support the latest release of Fastify anyway.

Could you bump the fastify dep on package.json too?

**Comment by darkgl0w** [comment]
Should I bump the minimum required `fastify` version required to 3.x too ?

Currently require `fastify@1.0.0` or greater:
```js
module.exports = fp(fastifyNext, {
  fastify: '>=1.0.0',
  name: 'fastify-nextjs'
})
```

**Comment by Eomm** [comment]
> Should I bump the minimum required fastify version to >=3.22.1 too ?

Not sure about it because someone out there could be using Fastify v2 and this plugin (and I know this is not a hypothesis).
If we do it, we should bump a major.

**Comment by mcollina** [comment]
let's bump the minimum dependency on Fastify (and use the ~ instead of the ^) and bump the major.

**Comment by darkgl0w** [comment]
@Eomm > yeah this is why at first I just added an `istanbul ignore next` command without removing the check. Like this it allowed to ensure compatibility with old fastify version.

Anyway with those 2 statements being removed we must land this as a major since this is a breaking change with fastify <= v3.22.0

**Comment by darkgl0w** [comment]
> let's bump the minimum dependency on Fastify (and use the ~ instead of the ^) and bump the major.

@mcollina > I already bumped all dependencies to their latest (both in `package.json` and `package-lock.json`) it should be enough and with this last change fastify plugin constraints will do the job if it detects an unsupported version ^^

**Review by Eomm — APPROVED** [review]

**Comment by Eomm** [comment]
(waiting before merge: there are a `minor` in pipeline to release first)

**Pull request merged**
