### PR TITLE
Fix TypeScript declaration of `app` argument in callback

### PR DESCRIPTION
**Pull request by KODerFunk**
### Reason

I use Next.js `app` argument wider than just method `getRequestHandler`, that repeats on both `DevServer` and `NextServer`. But it different objects, and now `DevServer` is mistake. 

For access for real `DevServer` (It would be more correct to say `Server` — ancestor of `DevServer`, which only in development mode) you can use `app.server.*`.

#### Checklist

- [x] run `npm run test`
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Could you add a test for the type? See https://github.com/fastify/fastify-nextjs/blob/master/types.test.ts

**Comment by KODerFunk** [comment]
@mcollina I add, but it "strange" test for typings. 

Maybe one of following movements I will help to port the library's main code to the TS? Then there is no need to test the types separately, and file with the types will simply be generated before package is released.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by KODerFunk** [comment]
@mcollina What's next? Sorry, but I need to schedule a package update in the project 😊

**Comment by KODerFunk** [comment]
@mcollina, rebased. Conflict resolved.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
