### PR TITLE
ci: enable license checking

### PR DESCRIPTION
**Pull request by Fdawgs**
See https://github.com/fastify/workflows/issues/49

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
@mcollina 

Found CC-BY-4.0 licensed package

**Comment by mcollina** [comment]
what package?

**Comment by Uzlopak** [comment]
@mcollina 

`Package "caniuse-lite@1.0.30001299" is licensed under "CC-BY-4.0" which is not permitted by the --onlyAllow flag. Exiting.`

**Comment by Fdawgs** [comment]
next itself depends on that directly.

**Comment by Uzlopak** [comment]
I really dont know how we can handle this and be on the safe side. I kind of cant imagine to add CC-BY-4.0 to the licensechecker allowed list.

**Comment by mcollina** [comment]
we should add a parameter to the action

**Comment by Uzlopak** [comment]
Like 

license-checker: true
license-checker-allowed: MIT;ISC 

?

**Comment by mcollina** [comment]
Yes

**Comment by Uzlopak** [comment]
@Fdawgs 

Ok?

**Pull request merged**
