### PR TITLE
fix: update under-pressure -> @fastify/under-pressure

### PR DESCRIPTION
**Pull request by rriski**
Fixes https://github.com/fastify/fastify-nextjs/issues/549.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ x commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by kibertoad** [comment]
@Fdawgs I assume ci workflows need to be updated to v4 too?

**Comment by Fdawgs** [comment]
> @Fdawgs I assume ci workflows need to be updated to v4 too?

Nah, this repo is already using the shared workflow. 😸

**Review by kibertoad — APPROVED** [review]

**Comment by SimenB** [comment]
Release? 😀

**Comment by SimenB** [comment]
@mcollina this should have been released in v9, no? `@fastify/under-pressure@7` is fastiify v4 only

**Comment by mcollina** [comment]
Then this should not have been released at all

**Pull request merged**
