### PR TITLE
fix `next()` type declaration

### LINKED ISSUE #207: TypeScript error
## 🐛 Bug Report

It is clear that that are types for fastify-nextjs and from what I can tell the types look ok with [a 'next' method being applied to fastify](https://github.com/fastify/fastify-nextjs/blob/master/index.d.ts#L20). The problem is that it is not being applied properly in my relatively simple application.

## To Reproduce

```ts
import fastify, { RequestGenericInterface } from "fastify";
import fastifyNext from 'fastify-nextjs';

const app = fastify({ logger: true })
    .register(fastifyNext)
    .after(() => {
        fastify.next('/hello')
    });

```

## Expected behavior

I expect there not to be a typescript error that says 

```
Property 'next' does not exist on type '{ <Server extends Http2SecureServer, Request extends RawRequestDefaultExpression<Server> = RawRequestDefaultExpression<Server>, Reply extends RawReplyDefaultExpression<...> = RawReplyDefaultExpression<...>, Logger extends FastifyLoggerInstance = FastifyLoggerInstance>(opts: FastifyHttp2SecureOptions<...>): FastifyIn...'.ts(2339)

```

## Your Environment

- *node version*:  12
- *fastify version*: >=2.0.0
- *os*: Mac
- ts-node

### PR DESCRIPTION
**Pull request by Iamshankhadeep**
fixes #207 
- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Could you please add a test to https://github.com/fastify/fastify-nextjs/blob/master/types.test.ts?

**Comment by Iamshankhadeep** [comment]
hey @mcollina actually I am not sure about what kind of test do I need to include? Any guidance will be helpful. Btw from what can I understand `types.test.ts` does not cotain any tests, or am I wrong about something?

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by Iamshankhadeep** [comment]
Any update on this? Need a bit help too. To close this ASAP

**Comment by climba03003** [comment]
I do not see any difference between the two style of function declaration. Even without this update, I can use the typing normally.

**Comment by climba03003** [comment]
@Iamshankhadeep Thanks for your PR. It is actually no bug for #207.

**Pull request closed without merging**
