### PR TITLE
disable package-lock, pin next version

### LINKED ISSUE #592: Remove package-lock, 2nd try
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

As discussed and mentioned here: https://github.com/fastify/fastify-nextjs/issues/238

Nestjs is not using semver. So breaking changes are possible.

What if we still remove the package-lock and pin the version in the package.json? It should be the same effect as locking the versions, correct? I mean i checked the package.json of nestjs and they pin all the versions.

### PR DESCRIPTION
**Pull request by Uzlopak**
Resolves #592 

Removes the package-lock.json generation and pins the version of nextjs in the package.json to ensure, that we get dependabot PRs and make us keep track that our code is potentially up to date with latest nextjs.

Imho the information that nextjs is a peerDepenedncy, were we expect that nextjs is 9.x.x || 10.x.x || 11.x.x || 12.x.x semver is quite a stretch. Are we actually sure that this package is handling nextjs 9?

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
let's drop the extended range for peerDeps

**Comment by mcollina** [comment]
We need the package-lock to get dependabot updates for deep dependencies. This was added here because next (& deps) is not supposed to be run without.

**Comment by Uzlopak** [comment]
@mcollina 

If we pin next version we should still get dependabot updates regarding next. Or are you referring to react and those deps? Arent those using semver? So why do we need them to be always be latest version? 

What is the benefit of shipping package-lock.json?

**Comment by mcollina** [comment]
> If we pin next version we should still get dependabot updates regarding next. Or are you referring to react and those deps? 

I'm referring to those, TypeScript and others. The complexities of modern frontend stacks makes all of them susceptible to breakages even in the minor and patch ranges.
This module was broken multiple times by this. The package-lock is critical for these dependencies.

> Arent those using semver? So why do we need them to be always be latest version?

We need to know the latest version where tests where passing.

**Comment by Uzlopak** [comment]
What do you mean with 

`let's drop the extended range for peerDeps`

**Comment by mcollina** [comment]
> Imho the information that nextjs is a peerDepenedncy, were we expect that nextjs is 9.x.x || 10.x.x || 11.x.x || 12.x.x semver is quite a stretch. Are we actually sure that this package is handling nextjs 9?

Just use latest major.

**Pull request closed without merging**
