### PR TITLE
ISSUE-52 PR (Object assignment)

### PR DESCRIPTION
**Pull request by jimmiehansson**
**Description**
This is a PR in reference to #52 see for further details.

### CODE REVIEW

**Comment by mcollina** [comment]
Can you add a test?

**Comment by jimmiehansson** [comment]
Sure thing, i need a vacation ☀️

**Comment by jimmiehansson** [comment]
This is probably the most lame follow up to an open PR in history, but i'll fix it. The month has been havoc, sorry guys! That test will get there

**Comment by jimmiehansson** [comment]
Sorry for the delay

**Pull request merged**
