### PR TITLE
plugin logLevel

### PR DESCRIPTION
**Pull request by PabloSzx**
As it is right now, it is impossible to customize the logging level of the Next.js routes, even though the plugin type definitions have autoComplete for `logLevel`, and this PR reuses the plugin options `logLevel` config.

The test added fails if the changes in `index.js` are reverted.

### CODE REVIEW

**Comment by PabloSzx** [comment]
The tests are failling in CI but in local they are fine 🤔

**Comment by zekth** [comment]
> The tests are failling in CI but in local they are fine 🤔

```
          diff: |
            --- expected
            +++ actual
            @@ -1,1 +1,1 @@
            -application/javascript; charset=UTF-8
            +text/html; charset=utf-8
          ...
```

May you missed committing something?

**Comment by PabloSzx** [comment]
> > The tests are failling in CI but in local they are fine 🤔
> 
> ```
>           diff: |
>             --- expected
>             +++ actual
>             @@ -1,1 +1,1 @@
>             -application/javascript; charset=UTF-8
>             +text/html; charset=utf-8
>           ...
> ```
> 
> May you missed committing something?

No, everything is fine, 56/56 passed, but the coverage is picking up the .next files, but I didn't change anything about that

**Comment by zekth** [comment]
Indeed. Your tests are ok as i see. Maybe another PR to fix this issue. Any idea @fastify/plugins ?

**Comment by mcollina** [comment]
A PR that fixes this would be welcomed, yes. Let's commit the lockfile for this one as it seems minor version of Next.js are breaking.

**Comment by PabloSzx** [comment]
> Let's commit the lockfile for this one as it seems minor version of Next.js are breaking.

done 👍

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
